### DISCUSSION TITLE
Welcome to EasyOpenTherm Discussions!

### DISCUSSION THREAD

**Discussion by Jeroen88** [Jeroen88/EasyOpenTherm#4] [Announcements]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

**Comment by craigsbits** [comment]
@Jeroen88 I have been running the script without connecting it to a boiler as I am a bit excited to be able to interface with my future boiler currently sitting in a box!  I have been confused that my published 'local_temperature' does not change after the initial published value.  I am now sure this is intentional am I correct?

Thanks for such a complete bit of code for Home Assistant.

**Comment by Jeroen88** [comment]
Hi @craigsbits, 

Did you read this in the examples README? You need:

A thermometer in Home Assistant, and an automation to forward the room temperature to the Thermostat using a Home Assistant Automation (Settings -> Automations & Scenes -> + Create Automation. Start with an empty automation, click the three dots in the upper right corner and select: Edit in YAML). Add:

```
alias: Publish room temperature
description: Publish room temperature to MQTT Climate state
trigger:
  - platform: state
    entity_id: sensor.temperature_humidity_sensor_2258_temperature
action:
  - service: mqtt.publish
    data:
      topic: Metriot/EasyOpenTherm/22b5ea03f784/climate/state
      payload: "{\"temperature\":{{ trigger.to_state.state }}}"
mode: single

```

The entity (```sensor.temperature_humidity_sensor_2258_temperature```)  should be the thermometer in Home Assistant that you want to use, e.g. a thermometer in your living room.

The ID in the topic (```22b5ea03f784``` in ```Metriot/EasyOpenTherm/22b5ea03f784/climate/state```) should be your own ID (can be found by looking at the logging of the ESP). You may also be able to find it by looking in Home Assistant at Settings -> Devices & Services -> Core Mosquitto and then fill in at "Topic to subscibe to" "Metriot/EasyOpenTherm/#" and press start listening. After a while you should see messages coming in.

The temperature is only updated if the room temperature changes.

Also in the README:
Thermostat behaviour
- The thermostat is enabled in Home Assistant if it communicates with an OpenTherm boiler
- The thermostat shows the room temperature if it receives temperature updates over MQTT (and is enabled, see previous step)

Since I understand that your boiler is not connected yet, the Climate still is shown in Home Assistant, but greyed out and temperatures are not updated (yet)

Does this help? If not please ask again!
